#pragma line 1 "maccell/src/macc.cpp" ::: -10
#pragma line 1 "maccell/src/macc.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 156 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 413 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 427 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "maccell/src/macc.cpp" 2 ::: 194
#pragma line 1 "maccell/src/macc.h" 1 ::: 203
#pragma line 20 "maccell/src/macc.h" ::: 210
#pragma line 9 "maccell/src/macc.cpp" 2 ::: 239
