#pragma line 1 "maccell/src/macc.cpp" ::: 0
#pragma line 1 "maccell/src/macc.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/opt/Xilinx/SDx/2017.2/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "maccell/src/macc.cpp" 2 ::: 204
#pragma line 1 "maccell/src/macc.h" 1 ::: 213
#pragma line 20 "maccell/src/macc.h" ::: 220
#pragma line 9 "maccell/src/macc.cpp" 2 ::: 249
