// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmacc_par_convs.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMacc_par_convs_CfgInitialize(XMacc_par_convs *InstancePtr, XMacc_par_convs_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMacc_par_convs_Start(XMacc_par_convs *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMacc_par_convs_IsDone(XMacc_par_convs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMacc_par_convs_IsIdle(XMacc_par_convs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMacc_par_convs_IsReady(XMacc_par_convs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMacc_par_convs_EnableAutoRestart(XMacc_par_convs *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMacc_par_convs_DisableAutoRestart(XMacc_par_convs *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XMacc_par_convs_InterruptGlobalEnable(XMacc_par_convs *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_GIE, 1);
}

void XMacc_par_convs_InterruptGlobalDisable(XMacc_par_convs *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_GIE, 0);
}

void XMacc_par_convs_InterruptEnable(XMacc_par_convs *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_IER);
    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XMacc_par_convs_InterruptDisable(XMacc_par_convs *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_IER);
    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XMacc_par_convs_InterruptClear(XMacc_par_convs *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMacc_par_convs_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XMacc_par_convs_InterruptGetEnabled(XMacc_par_convs *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_IER);
}

u32 XMacc_par_convs_InterruptGetStatus(XMacc_par_convs *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMacc_par_convs_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMACC_PAR_CONVS_CTRL_BUS_ADDR_ISR);
}

