// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmacc_par_convs.h"

extern XMacc_par_convs_Config XMacc_par_convs_ConfigTable[];

XMacc_par_convs_Config *XMacc_par_convs_LookupConfig(u16 DeviceId) {
	XMacc_par_convs_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMACC_PAR_CONVS_NUM_INSTANCES; Index++) {
		if (XMacc_par_convs_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMacc_par_convs_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMacc_par_convs_Initialize(XMacc_par_convs *InstancePtr, u16 DeviceId) {
	XMacc_par_convs_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMacc_par_convs_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMacc_par_convs_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

