// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMACC_PAR_CONVS_H
#define XMACC_PAR_CONVS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmacc_par_convs_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XMacc_par_convs_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XMacc_par_convs;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMacc_par_convs_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMacc_par_convs_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMacc_par_convs_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMacc_par_convs_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMacc_par_convs_Initialize(XMacc_par_convs *InstancePtr, u16 DeviceId);
XMacc_par_convs_Config* XMacc_par_convs_LookupConfig(u16 DeviceId);
int XMacc_par_convs_CfgInitialize(XMacc_par_convs *InstancePtr, XMacc_par_convs_Config *ConfigPtr);
#else
int XMacc_par_convs_Initialize(XMacc_par_convs *InstancePtr, const char* InstanceName);
int XMacc_par_convs_Release(XMacc_par_convs *InstancePtr);
#endif

void XMacc_par_convs_Start(XMacc_par_convs *InstancePtr);
u32 XMacc_par_convs_IsDone(XMacc_par_convs *InstancePtr);
u32 XMacc_par_convs_IsIdle(XMacc_par_convs *InstancePtr);
u32 XMacc_par_convs_IsReady(XMacc_par_convs *InstancePtr);
void XMacc_par_convs_EnableAutoRestart(XMacc_par_convs *InstancePtr);
void XMacc_par_convs_DisableAutoRestart(XMacc_par_convs *InstancePtr);


void XMacc_par_convs_InterruptGlobalEnable(XMacc_par_convs *InstancePtr);
void XMacc_par_convs_InterruptGlobalDisable(XMacc_par_convs *InstancePtr);
void XMacc_par_convs_InterruptEnable(XMacc_par_convs *InstancePtr, u32 Mask);
void XMacc_par_convs_InterruptDisable(XMacc_par_convs *InstancePtr, u32 Mask);
void XMacc_par_convs_InterruptClear(XMacc_par_convs *InstancePtr, u32 Mask);
u32 XMacc_par_convs_InterruptGetEnabled(XMacc_par_convs *InstancePtr);
u32 XMacc_par_convs_InterruptGetStatus(XMacc_par_convs *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
